In [1]:
import numpy as np
arr = np.random.randint (-50, 50, size = (1, 25))
M = arr.reshape (5, 5)
print (M)


[[-27   0  -7 -26 -49]
 [ -9 -32 -10  21 -42]
 [ -6  35  46  33 -49]
 [-25 -21  34  18  -8]
 [ 47  22 -22 -48  37]]


In [2]:
mul = np.matmul(M, M)
dot = np.dot(M, M)
print(mul)
print(dot)

[[ -882  -777    61  2355    61]
 [-1908  -691  1561  1626   553]
 [-3557 -1281  4008  5355 -5507]
 [ -166  1308  2737  2039     1]
 [ 1604   348 -4007 -4126  -396]]
[[ -882  -777    61  2355    61]
 [-1908  -691  1561  1626   553]
 [-3557 -1281  4008  5355 -5507]
 [ -166  1308  2737  2039     1]
 [ 1604   348 -4007 -4126  -396]]


In [6]:
X = np.resize(arr, (3,5))
print (X)


[[-27   0  -7 -26 -49]
 [ -9 -32 -10  21 -42]
 [ -6  35  46  33 -49]]


In [22]:
dot = np.dot(X, M)
print(dot)

dot = np.dot(2, M)
print(dot)

mul = np.matmul(X, M)
print(mul)

mul = np.matmul(2, M) # throws error because scalars don't work in matmul
print(mul)

[[ -882  -777    61  2355    61]
 [-1908  -691  1561  1626   553]
 [-3557 -1281  4008  5355 -5507]]
[[-54   0 -14 -52 -98]
 [-18 -64 -20  42 -84]
 [-12  70  92  66 -98]
 [-50 -42  68  36 -16]
 [ 94  44 -44 -96  74]]
[[ -882  -777    61  2355    61]
 [-1908  -691  1561  1626   553]
 [-3557 -1281  4008  5355 -5507]]


ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)